# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bebop}
  s.version = "1.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["John Bender"]
  s.date = %q{2010-06-02}
  s.description = %q{A small Sinatra/Monk extension for resource routing}
  s.email = %q{john.m.bender@gmail.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "README.markdown",
     "Rakefile",
     "bebop.gemspec",
     "examples/filters.rb",
     "examples/routes.rb",
     "lib/bebop.rb",
     "lib/bebop/ext.rb",
     "spec/bebop_spec.rb"
  ]
  s.homepage = %q{http://github.com/johnbender/bebop}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A small Sinatra/Monk extension for resource routing}
  s.test_files = [
    "spec/bebop_spec.rb",
     "examples/routes.rb",
     "examples/filters.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.5"])
      s.add_runtime_dependency(%q<sinatra>, ["= 1.0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<activesupport>, [">= 2.3.5"])
      s.add_dependency(%q<sinatra>, ["= 1.0"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 2.3.5"])
    s.add_dependency(%q<sinatra>, ["= 1.0"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

